---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../components/db
  - ../../components/app
namespace: tandoor
images:
  - name: vabene1111/recipes
    newTag: latest
  - name: nginx
    newTag: latest
  - name: docker.io/bitnami/postgresql
    newTag: 11.5.0-debian-9-r60
