---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
namespace: tandoor
namePrefix: "tandoor-"
commonLabels:
  app: tandoor
  tier: application
configMapGenerator:
  - name: nginx-config
    files:
      - nginx-config
  - name: postgres-config
    envs:
      - postgres.env
  - name: app-config
    envs:
      - app.env
