---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  sessionAffinity: None
  clusterIP: None
